"""Generate lab/state/now.md — daily snapshot of bert's current state.

A daily /now page following the Sivers convention with a
Mandala-format ring structure.

The /now page is bert's at-a-glance current state for the PI to read
each morning. Concentric rings map onto VSM systems (S1 inner /
operations through S5 outer / governance).

Run manually:
  .venv/bin/python tools/generate_now_page.py

Or as a cron entry (PI runs once):
  0 6 * * *  /path/to/Desktop/bert-lab/.venv/bin/python /path/to/Desktop/bert-lab/tools/generate_now_page.py
"""

import datetime
import json
import sys
from pathlib import Path

LAB_ROOT = Path(__file__).resolve().parent.parent
NOW_PATH = LAB_ROOT / "lab" / "state" / "now.md"


def _safe_read(path: Path, lines: int = 0) -> str:
    """Read file, return empty string if missing. Optionally cap to N lines."""
    if not path.exists():
        return ""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""
    if lines > 0:
        return "\n".join(text.split("\n")[:lines])
    return text


def _count_proposed_patterns() -> tuple[int, int]:
    procedures = _safe_read(LAB_ROOT / "memories" / "procedures.md")
    proposed = procedures.count("STATUS:** PROPOSED")
    frozen = procedures.count("STATUS:** FROZEN")
    return proposed, frozen


def _count_seasoning() -> tuple[int, int]:
    """Returns (total_unrevived, total_all)."""
    sjson = LAB_ROOT / "lab" / "sod" / "seasoning.jsonl"
    if not sjson.exists():
        return 0, 0
    unrevived = 0
    total = 0
    try:
        with sjson.open() as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    e = json.loads(line)
                    total += 1
                    if not e.get("revived_at"):
                        unrevived += 1
                except json.JSONDecodeError:
                    continue
    except OSError:
        pass
    return unrevived, total


def _last_d_n() -> str:
    """Most recent D-N entry from log.md (newest is first)."""
    log = _safe_read(LAB_ROOT / "memories" / "log.md", lines=2)
    for line in log.split("\n"):
        if line.startswith("## D-"):
            return line.replace("## ", "")
    return "(no D-N entries yet)"


def _phase_status() -> str:
    """Read the current phase position from current.md."""
    current = _safe_read(LAB_ROOT / "memories" / "current.md")
    for line in current.split("\n"):
        if "Phase URGENT" in line or "Phase H1" in line or "Phase H2" in line:
            return line.strip("- ").strip()
    return "(phase status unclear; see memories/current.md)"


def _last_cycle_exit() -> str:
    exit_file = LAB_ROOT / "state" / "session_exit.md"
    if exit_file.exists():
        return _safe_read(exit_file).split("\n")[0].strip() or "(empty)"
    return "(no session_exit.md)"


def _backup_count() -> int:
    backup_dir = LAB_ROOT / "backup" / "state"
    if not backup_dir.exists():
        return 0
    return len(list(backup_dir.glob("state_*.tar.gz")))


def render_now_page() -> str:
    """Compose the /now page content."""
    ts = datetime.datetime.now(datetime.UTC)
    proposed, frozen = _count_proposed_patterns()
    seasoned_unrev, seasoned_total = _count_seasoning()
    last_dn = _last_d_n()
    phase = _phase_status()
    last_exit = _last_cycle_exit()
    backups = _backup_count()

    parts = [
        f"# bert /now — {ts.strftime('%Y-%m-%d')} (UTC)",
        "",
        "*Generated by `tools/generate_now_page.py` (Sivers `/now` convention + Mandala-format ring structure). VSM 5-system layout: outer ring = governance (S5), inner = operations (S1).*",
        "",
        "---",
        "",
        "## Outer ring — S5 Policy / Governance",
        "",
        f"- **Pattern catalogue:** {frozen} frozen + {proposed} proposed = {frozen + proposed} total",
        f"- **Most recent ratification:** `{last_dn}`",
        f"- **Backup discipline (P-015):** {backups} state-backup tar.gz under `backup/state/`",
        "",
        "## Ring 4 — S4 Intelligence / Scanning",
        "",
        "- **Recent research:** check `findings/researcher_*.md` (R-series) for latest scans",
        "- **Provider deprecation calendar (P-025):** see `lab/sod/deprecation_calendar.md`" + (" (file exists)" if (LAB_ROOT / "lab" / "sod" / "deprecation_calendar.md").exists() else " (file pending; will be populated on first deprecation tracked)"),
        "",
        "## Ring 3 — S3 Operations Management / Director",
        "",
        f"- **Build phase:** {phase}",
        f"- **Last cycle exit:** {last_exit}",
        "- **Cycle queue:** see `state/cycle_queue.md`",
        "",
        "## Ring 2 — S2 Coordination / Evaluator",
        "",
        f"- **Seasoning queue (P-VS-09):** {seasoned_unrev} unrevived / {seasoned_total} total entries",
        "- **Cross-family judges:** see `core/subagent.py:227` `pick_evaluator_model` for current MODEL_FAMILIES register",
        "",
        "## Inner ring — S1 Operations / Implementer",
        "",
        "- **Smoke tests:** see `tests/_smoke_*.py`; run via `.venv/bin/python tests/_smoke_<suite>.py`",
        "- **Most recent commit:** see `git log --oneline -1`",
        "",
        "---",
        "",
        f"*Last generated: {ts.isoformat()}. To regenerate: `.venv/bin/python tools/generate_now_page.py`. Cron entry: `0 6 * * * .../generate_now_page.py`.*",
    ]
    return "\n".join(parts) + "\n"


def main() -> int:
    NOW_PATH.parent.mkdir(parents=True, exist_ok=True)
    content = render_now_page()
    NOW_PATH.write_text(content)
    print(f"wrote {NOW_PATH} ({len(content)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
